/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class URLEscape */

#ifndef _Included_URLEscape
#define _Included_URLEscape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     URLEscape
 * Method:    escape
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_URLEscape_escape
  (JNIEnv *, jclass, jstring);

/*
 * Class:     URLEscape
 * Method:    unescape
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_URLEscape_unescape
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
